import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { homePath } from "./agents";

/**
 * OpenCode hook bridge. OpenCode has no settings.json-style shell hook list —
 * it auto-loads plugins exporting a function that returns a Hooks object
 * (see teamai-cli's opencode-hooks for the same mechanism). soloteam's plugin
 * is deliberately tiny: session start pulls, idle pushes.
 */

export const OPENCODE_PLUGIN_FILE = "soloteam-hooks.ts";
export const OPENCODE_MARKER = "[soloteam]";

export function opencodePluginDir(): string {
  return join(homePath(".config", "opencode"), "plugin");
}

export function opencodePluginPath(): string {
  return join(opencodePluginDir(), OPENCODE_PLUGIN_FILE);
}

export function buildOpencodePlugin(binCommand: string, dir: string): string {
  return `// ${OPENCODE_MARKER} hooks plugin — generated by soloteam, do not edit by hand.
// Pulls shared config on session start, pushes changes when idle.
// Errors are swallowed; sync must never block the agent.
import { execFile } from "node:child_process";

function run(args: string[]): void {
  try {
    const child = execFile(${JSON.stringify(binCommand)}, args, { timeout: 60_000 }, () => undefined);
    child.unref?.();
  } catch {
    // never block the agent
  }
}

/** @param {{ directory?: string }} _ctx */
export const SoloteamHooks = async (_ctx: unknown) => {
  return {
    event: async ({ event }: { event?: { type?: string } }) => {
      if (event?.type === "session.created") {
        run(["pull", "--dir", ${JSON.stringify(dir)}]);
      } else if (event?.type === "session.idle") {
        run(["push", "--dir", ${JSON.stringify(dir)}]);
      }
    },
  };
};
`;
}

/** Write (or refresh) the plugin. Idempotent — rewrites the file each time. */
export async function injectOpencodePlugin(binCommand: string, dir: string): Promise<string> {
  const pluginDir = opencodePluginDir();
  await mkdir(pluginDir, { recursive: true });
  const path = opencodePluginPath();
  await writeFile(path, buildOpencodePlugin(binCommand, dir), "utf8");
  return path;
}

export async function removeOpencodePlugin(): Promise<boolean> {
  const path = opencodePluginPath();
  if (!existsSync(path)) return false;
  const raw = await readFile(path, "utf8").catch(() => "");
  if (!raw.includes(OPENCODE_MARKER)) return false; // not ours — leave it alone
  await rm(path);
  return true;
}

export function opencodePluginInstalled(): boolean {
  return existsSync(opencodePluginPath());
}
